name: Deploy to server                                                                                                                          
                  
on:
    push:
      branches:
        - master                                                                                                                                              
jobs:
    deploy:                                                                                                                                       
      runs-on: ubuntu-latest
      steps:
        - name: Deploy via SSH
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: 149.210.164.162
            username: admin                                                                                                                       
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |                                                                                                                             
              cd /home/admin/domains
              git pull
